# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('traffic-simulation', ['core'])
    module.source = [
        'model/traffic-simulation.cc',
        'helper/traffic-simulation-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('traffic-simulation')
    module_test.source = [
        'test/traffic-simulation-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'traffic-simulation'
    headers.source = [
        'model/traffic-simulation.h',
        'helper/traffic-simulation-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

