# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('path-hashing-adv-example', ['path-hashing-adv'])
    obj.source = 'path-hashing-adv-example.cc'

