# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('custom-switches', ['core'])
    module.source = [
        'model/custom-switches.cc',
        'helper/custom-switches-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('custom-switches')
    module_test.source = [
        'test/custom-switches-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'custom-switches'
    headers.source = [
        'model/custom-switches.h',
        'helper/custom-switches-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

